CREATE DATABASE DB_CIO
USE DB_CIO


--TABLA CAMIONERO CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE TABLE CAMIONERO
(
CED_CAMIONERO VARCHAR(20) PRIMARY KEY,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
TELEFONO VARCHAR(20),
DIRECCION VARCHAR(20),
SALARIO FLOAT
)

--TABLA CAMIONES CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE TABLE CAMIONES
(
MATRICULA VARCHAR(20) PRIMARY KEY,
CED_CAMIONERO VARCHAR(20),
POTENCIA VARCHAR(10),
MODELO VARCHAR(15),	
TIPO VARCHAR(20)
)

--CREACION DE LA LLAVE FORANEA A CAMIONERO CRISTIAN RIVERA MUÑOZ

ALTER TABLE CAMIONES
ADD CONSTRAINT FK_CAMIONES_CED_CAMINERO_CAMIONERO_CED_CAMIONERO
FOREIGN KEY(CED_CAMIONERO)
REFERENCES CAMIONERO (CED_CAMIONERO)

--PRUEBA DE  FORANEA CRISTIAN RIVERA MUÑOZ

SELECT * FROM CAMIONERO, CAMIONES WHERE CAMIONERO.CED_CAMIONERO='10045'



--PROCEDIMIENTO DE GUARDAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_GUARDAR_CAMIONERO
@CED_CAMIONERO VARCHAR(20),
@NOMBRE VARCHAR(20),
@APELLIDO VARCHAR(20),
@TELEFONO VARCHAR(20),
@DIRECCION VARCHAR(20),
@SALARIO VARCHAR(20)
AS
BEGIN
INSERT INTO CAMIONERO(CED_CAMIONERO,NOMBRE,APELLIDO,TELEFONO,DIRECCION,SALARIO)
VALUES(@CED_CAMIONERO,@NOMBRE,@APELLIDO,@TELEFONO,@DIRECCION,@SALARIO)
END

EXECUTE USP_GUARDAR_CAMIONERO '100','PEPO','RAMIREZ','121212','C14#45-45','100025'
EXECUTE USP_GUARDAR_CAMIONERO '10045','LUCA','MUÑOZ','1245454','C24#44-95','12121100025'
EXECUTE USP_GUARDAR_CAMIONERO '1045','LUCAS','PEREZ','1245454','C24#90-95','1214545848'

SELECT * FROM CAMIONERO


--PROCEDIMIENTO DE GUARDAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_GUARDAR_CAMIONES
@MATRICULA VARCHAR(10),
@CED_CAMIONERO VARCHAR(20),
@POTENCIA VARCHAR(10),
@MODELO VARCHAR(15),
@TIPO VARCHAR(20)
AS
BEGIN
INSERT INTO CAMIONES(MATRICULA,CED_CAMIONERO,POTENCIA,MODELO,TIPO)
VALUES(@MATRICULA,@CED_CAMIONERO,@POTENCIA,@MODELO,@TIPO)
END

EXECUTE USP_GUARDAR_CAMIONES '100A2','10045','25CV','VOLVO 2015','DOBLE TROQUE'


--PROCEDIMIENTO DE ACTUALIZAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_ACTUALIZAR_CAMIONERO
@CED_CAMIONERO VARCHAR(20),
@NOMBRE VARCHAR(20),
@APELLIDO VARCHAR (20),
@TELEFONO VARCHAR(20),
@DIRECCION VARCHAR(20),
@SALARIO VARCHAR(20)
AS
BEGIN
UPDATE CAMIONERO SET NOMBRE=@NOMBRE,APELLIDO=@APELLIDO,TELEFONO=@TELEFONO,DIRECCION=@DIRECCION,SALARIO=@SALARIO
WHERE CED_CAMIONERO=@CED_CAMIONERO
END

EXECUTE USP_ACTUALIZAR_CAMIONERO '100','PEDRO','RODRIGUEZ','121212','C14#45-45','100025'

--PROCEDIMIENTO DE ACTUALIZAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP__ACTULIZAR_CAMIONES
@MATRICULA VARCHAR(20),
@CED_CAMIONERO VARCHAR(20),
@POTENCIA VARCHAR(10),
@MODELO VARCHAR(15),
@TIPO VARCHAR(20)
AS
BEGIN
UPDATE CAMIONES SET CED_CAMIONERO=@CED_CAMIONERO,POTENCIA=@POTENCIA,MODELO=@MODELO,TIPO=@TIPO
WHERE MATRICULA=@MATRICULA
END
EXECUTE USP__ACTULIZAR_CAMIONES '100A2','100','25CV','VOLVO 2015','DOBLE TROQUE'


--PROCEDIMIENTO DE ELIMINAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_ELIMINAR_CAMIONERO
@CED_CAMIONERO VARCHAR(20)
AS
BEGIN
DELETE FROM CAMIONERO WHERE CED_CAMIONERO=@CED_CAMIONERO
END
EXECUTE  USP_ELIMINAR_CAMIONERO '1045'

--PROCEDIMIENTO DE ELIMINAR CREADA POR CRISTIAN RIVERA MUÑOZ
CREATE PROCEDURE USP_ELIMINAR_CAMIONES
@MATRICULA VARCHAR(20)
AS
BEGIN
DELETE FROM CAMIONES WHERE MATRICULA=@MATRICULA
END

EXECUTE USP_ELIMINAR_CAMIONES '100A2'

--PROCEDIMIENTO DE CONSULTAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_CONSULTAR_CAMIONERO
@CED_CAMIONERO VARCHAR(20)
AS
BEGIN
SELECT * FROM CAMIONERO WHERE CED_CAMIONERO=@CED_CAMIONERO
END
EXECUTE USP_CONSULTAR_CAMIONERO '10045'

--PROCEDIMIENTO DE CONSULTAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_CONSULTAR_CAMIONES
@MATRICULA VARCHAR(20)
AS
BEGIN
SELECT * FROM CAMIONES WHERE MATRICULA=@MATRICULA
END

EXECUTE USP_CONSULTAR_CAMIONES '100A2'


--PROCEDIMIENTO DE LISTAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_LISTIAR_CAMIONERO
AS
BEGIN
SELECT NOMBRE,SALARIO FROM CAMIONERO 
END
EXECUTE USP_LISTIAR_CAMIONERO 

--PROCEDIMIENTO DE LISTAR CREADA POR CRISTIAN RIVERA MUÑOZ

CREATE PROCEDURE USP_LISTAR_CAMIONES
AS
BEGIN
SELECT * FROM CAMIONES
END

EXECUTE USP_LISTAR_CAMIONES












